language: node_js

node_js:
- "10"

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - hkroh.nonoll@gmail.com
    on_success: always
    on_failure: always

install:
  - nvm install 10

before_install:
  - npm install

script:
  - npm run test

# 배포 설정 for heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: nonoll-todo-app
  on:
    repo: nonoll/todo-app