export enum TODO_EDITOR_MODE {
  ADD = 'TODO_EDITOR_ADD',
  MODIFY = 'TODO_EDITOR_MODIFY'
}

export enum TODO_ACTION_TYPES {
  DESCRIPTION = 'DESCRIPTION',
  PRIORITY = 'PRIORITY',
  DUE_DATE = 'DUE_DATE'
}
